CREATE TABLE `agent_memories` (
  `id` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '记忆唯一ID (UUID)',
  `user_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID',
  `namespace` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '命名空间，如 user:{id}:profile',
  `memory_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'profile / episode / procedural / lesson',
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '记忆正文（已摘要，建议控制长度）',
  `content_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容hash，用于快速去重',
  `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active' COMMENT 'active / superseded / conflict / deleted',
  `superseded_by` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '被哪条新记忆取代',
  `confidence` decimal(3,2) DEFAULT '1.00' COMMENT '置信度 0~1',
  `importance` tinyint DEFAULT '3' COMMENT '重要性 1~5',
  `source` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'agent_inferred' COMMENT 'user_explicit / user_feedback / agent_inferred / system',
  `source_thread_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源会话 thread_id',
  `source_job_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源任务 job_id',
  `qdrant_point_id` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '对应 Qdrant point id',
  `object_key` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MinIO/S3 对象key（原文）',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `expires_at` datetime(3) DEFAULT NULL COMMENT '过期时间，中期记忆用',
  `metadata` json DEFAULT NULL COMMENT '额外结构化信息',
  PRIMARY KEY (`id`),
  KEY `idx_user_ns_status` (`user_id`,`namespace`,`status`),
  KEY `idx_user_type_status` (`user_id`,`memory_type`,`status`),
  KEY `idx_status_expires` (`status`,`expires_at`),
  KEY `idx_content_hash` (`content_hash`),
  KEY `idx_superseded_by` (`superseded_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 中长期记忆主表';
