CREATE TABLE `financial_feature` (
  `code` text,
  `name` text,
  `report_date` datetime DEFAULT NULL,
  `revenue` double DEFAULT NULL,
  `net_profit` double DEFAULT NULL,
  `deduct_net_profit` double DEFAULT NULL,
  `roe` double DEFAULT NULL,
  `roa` double DEFAULT NULL,
  `gross_margin` double DEFAULT NULL,
  `net_margin` double DEFAULT NULL,
  `revenue_growth` double DEFAULT NULL,
  `profit_growth` double DEFAULT NULL,
  `operating_cashflow` double DEFAULT NULL,
  `fcf` text,
  `asset_liability_ratio` double DEFAULT NULL,
  `equity_multiplier` text,
  `eps` text,
  `bvps` double DEFAULT NULL,
  `ocfps` double DEFAULT NULL,
  `revenue_growth_qoq` double DEFAULT NULL,
  `profit_growth_qoq` double DEFAULT NULL,
  `fcf_ratio` double DEFAULT NULL,
  `leverage_score` double DEFAULT NULL,
  `quality_score` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
