CREATE TABLE `stock_factor` (
  `code` text,
  `name_tech` text,
  `date` datetime DEFAULT NULL,
  `trend_score` double DEFAULT NULL,
  `momentum_score` double DEFAULT NULL,
  `volume_score` double DEFAULT NULL,
  `total_technical_score` double DEFAULT NULL,
  `technical_rank` double DEFAULT NULL,
  `name_fin` text,
  `profitability_score` double DEFAULT NULL,
  `growth_score` double DEFAULT NULL,
  `quality_score` double DEFAULT NULL,
  `safety_score` double DEFAULT NULL,
  `total_financial_score` double DEFAULT NULL,
  `total_financial_rank` double DEFAULT NULL,
  `close` double DEFAULT NULL,
  `pe_ttm` double DEFAULT NULL,
  `pb` double DEFAULT NULL,
  `peg` double DEFAULT NULL,
  `valuation_score` double DEFAULT NULL,
  `total_composite_score` double DEFAULT NULL,
  `composite_rank` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
